IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = '$(DATABASE_NAME)')
BEGIN
  CREATE DATABASE $(DATABASE_NAME);
END;
GO

IF NOT EXISTS (SELECT name FROM master.sys.server_principals WHERE name = '$(DATABASE_USER)')
BEGIN
  CREATE LOGIN $(DATABASE_USER) WITH PASSWORD = '$(DATABASE_PASSWORD)';
END;
GO

USE $(DATABASE_NAME);
GO

IF NOT EXISTS (SELECT name FROM sys.database_principals WHERE name = '$(DATABASE_USER)')
BEGIN
  CREATE USER $(DATABASE_USER) FOR LOGIN $(DATABASE_USER);
END;
GO

sp_addrolemember 'db_owner', $(DATABASE_USER);
GO
